apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app133
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-namespace': tap-play
spec:
  type: service
  lifecycle: experimental
  owner: default-team
